### PR TITLE
Add refresh token field to login request

### PR DESCRIPTION
**Pull request by Fizzadar**

### CODE REVIEW

**Comment by tulir** [comment]
What's this for 🤔

Refresh tokens aren't supported

**Comment by Fizzadar** [comment]
Making it match the register req spec! Also need it for Babbleserv though can wrap the struct as workaround.

**Comment by tulir** [comment]
Oh yeah I guess ReqRegister already has it. Not sure if it's worth adding refresh token support anywhere right now though since auth will change with OIDC anyway.

mautrix-go clients will never send that field (so it will always be omitted), and servers can just ignore the field if they don't support refresh tokens. The field just says whether the client supports it, I'm pretty sure the server isn't required to serve a refresh token even if the client wants it

**Review by tulir — APPROVED** [review]

**Comment by Fizzadar** [comment]
> Oh yeah I guess ReqRegister already has it. Not sure if it's worth adding refresh token support anywhere right now though since auth will change with OIDC anyway.

Ah yeah that's a good point. I'll merge because it makes login:register structs complete, but agree not needed long term.

**Pull request merged**
